### ISSUE TITLE
App is not visible in the list to be added as an app

### ISSUE THREAD

**Issue by dhavalshah01** [estruyf/node-sppkg-deploy#2]
After the app has been deployed in the app catalog, the app is not visible to be added when we click on the "Add an App" or under the "Apps You can Add"

i am able to see the same app if i deploy it manually.

**Comment by estruyf** [comment]
Are you testing it on a developer tenant? If yes, did you leave the feature deployment property to true? If so, then it is normal that you cannot install it. This is because by setting the skip feature deploying to true, it will make the web parts automatically available tenant wide. More info can be found here: https://dev.office.com/sharepoint/docs/spfx/tenant-scoped-deployment

**Comment by dhavalshah01** [comment]
yeah, I figured that so already set the skipFeatureDeployment property to false. but still its not visible to be added.

![image](https://user-images.githubusercontent.com/13947393/29420910-0c1dbe18-8339-11e7-87ad-f5a5e82ad413.png)

**Comment by estruyf** [comment]
Ok, mistake on my side. Thanks! Will fix it.

**Comment by estruyf** [comment]
A new version is released that should solve this issue. You can install the new version via `npm install node-sppkg-deploy@1.1.1 --save`

**Comment by dhavalshah01** [comment]
Thanks Elio.. It is working  !

**Comment by estruyf** [comment]
You're welcome
